theme: minima
title: Mallory Blake
author: GitHub User
email: mallorykblake@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Mallory Blake practice projects and portfolio

# social links
twitter_username: MalKBlake1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
